# the docker setup has been especially
# inspired by the one used in this repository:
# https://github.com/mrcoles/node-react-docker-compose

version: '3'
services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
  server:
    build:
      context: ./server/
    volumes:
      - ./server/:/usr/app
      - /usr/app/node_modules
    ports:
      - '8000:8000'
    external_links:
      - mongo
    depends_on:
      - mongo
  web:
    build:
      context: ./web/
    volumes:
      - ./web/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - server
    ports:
      - '3000:3000'
